### PR TITLE
[SCOUT] datadome filter 1.3.0

### PR DESCRIPTION
**Pull request by guillaumewuip**
> [SCOUT]

## Description

The Envoy filter mentioned in Datadome documentation is in 1.3.0. We're using 1.2.0. Here is a PR to highlight the changes caused by backporting the 1.3.0 changes in our `datadome.lua` file.

https://docs.datadome.co/docs/module-envoy

### CODE REVIEW

**Comment by guillaumewuip** [comment]
See https://blablacar.slack.com/archives/C01GW7487GQ/p1695970747957579

**Review by frgaudet — APPROVED** [review]
I'm not a LUA specialist, but it seems ok :)

**Comment by frgaudet** [comment]
Closes CINF-2472

**Comment by frgaudet** [comment]
Closes CINF-2472

**Pull request merged**
